#2016-02-28 Evaluating Classifier Performance

In [1]:
import numpy as np
from sklearn import cross_validation
from sklearn import datasets
from sklearn import svm

In [4]:
#Load iris data:
iris = datasets.load_iris()
iris.data.shape, iris.target.shape

((150, 4), (150,))

In [6]:
#Train test split:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(
    iris.data, iris.target, test_size=0.4, random_state=0)

In [13]:
#Take a look at the data
X_train[0:5,:]

array([[ 6. ,  3.4,  4.5,  1.6],
       [ 4.8,  3.1,  1.6,  0.2],
       [ 5.8,  2.7,  5.1,  1.9],
       [ 5.6,  2.7,  4.2,  1.3],
       [ 5.6,  2.9,  3.6,  1.3]])

In [23]:
len(X_train), len(X_test)

(90, 60)

In [24]:
150*0.4

60.0

In [14]:
X_train[0,:]

array([ 6. ,  3.4,  4.5,  1.6])

In [15]:
X_train[0,0]

6.0

In [19]:
#Fit an SVM to the train data, test on test data:
clf_tt = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)
clf_tt.score(X_test, y_test)

0.96666666666666667

In [20]:
#Pretty easy and obtains a pretty high level of accuracy.

In [26]:
#Fit a SVM classifier to the data using cross-validation, folds=10:
clf = svm.SVC(kernel='linear', C=1)
scores = cross_validation.cross_val_score(clf, iris.data, iris.target, cv=5)

In [27]:
scores

array([ 0.96666667,  1.        ,  0.96666667,  0.96666667,  1.        ])

In [30]:
#Calculate mean and stdev of the scores from the CV
import numpy as np
np.mean(scores), np.std(scores)

(0.98000000000000009, 0.016329931618554516)

In [38]:
#Can also pass different scoring metrics to the cross_validation function:

clf_f1 = svm.SVC(kernel='linear', C=1)
scores_f1 = cross_validation.cross_val_score(clf_f1, iris.data, iris.target, cv=5, scoring='f1_weighted')

In [39]:
scores, np.mean(scores_f1), np.std(scores_f1)

(array([ 0.96658312,  1.        ,  0.96658312,  0.96658312,  1.        ]),
 0.9799498746867169,
 0.016370858765468191)